
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Providers from "./Components/Provider";
import Footer from "./Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const queryClient = new QueryClient()

 
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <Navbar></Navbar>
        </nav>
        <Providers>
          {children}
        </Providers>
        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
