
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Providers from "./Components/Provider";
import Footer from "./Components/Footer";
import ProtectedLayout from "./(prdected)/layout";
import ClientProvider from "./Components/ClitentProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <Navbar></Navbar>
        </nav>
        <ClientProvider>
            <Providers>
              {children}
            </Providers>
        </ClientProvider>

        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
